<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageUserClient.aspx.cs" Inherits="GrowTogetherClient.ManageUserClient" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage USer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <form id="form1" runat="server">
        Add New User&nbsp;
         <asp:Button runat="server" ID="Button1" Text="Add" OnClick="Button1_Click" />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AllowPaging="true"
            PageSize="10" AutoGenerateDeleteButton="True" AutoGenerateEditButton="False" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="UserId">
            <Columns>
                <asp:BoundField ItemStyle-Width="150px" DataField="UserID" HeaderText="User ID" />
                <asp:BoundField ItemStyle-Width="150px" DataField="Name" HeaderText="Customer ID" />
                <asp:BoundField ItemStyle-Width="150px" DataField="Email" HeaderText="Email" />
                <asp:BoundField ItemStyle-Width="150px" DataField="Gender" HeaderText="Gender" />
                <asp:BoundField ItemStyle-Width="150px" DataField="Phone" HeaderText="Phone" />

            </Columns>
        </asp:GridView>
        <div>
        </div>
    </form>
</body>
</html>
