<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserSuggestion.aspx.cs" Inherits="GrowTogetherClient.UserSuggestion" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
             <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AllowPaging="true"
     PageSize="10" AutoGenerateDeleteButton="False" AutoGenerateEditButton="False"  >
    <Columns>
        <asp:BoundField ItemStyle-Width="150px" DataField="msgId" HeaderText="Message ID" />
        <asp:BoundField ItemStyle-Width="150px" DataField="msgsubject" HeaderText="Subject" />
        <asp:BoundField ItemStyle-Width="150px" DataField="msgdes" HeaderText="Description" />
        

    </Columns>
</asp:GridView>
        </div>
    </form>
</body>
</html>
